---
# tasks file for bamboo
# - include_tasks: jdk-{{ ansible_os_family }}.yml
#   when: bamboo_master_include_jdk

- name: Install, configure, java | RedHat.
  ansible.builtin.yum:
    name: "java-{{ bamboo_master_openjdk_version }}-openjdk"
    state: installed
  when: ansible_os_family == 'RedHat'

- name: Install, configure, java | Debian.
  when: ansible_os_family == 'Debian'
  block:
    - name: Add OpenJDK PPA for Ubuntu 14.04 and lower
      ansible.builtin.apt_repository:
        repo: ppa:openjdk-r/ppa
      when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version <= "14")

    - name: Install OpenJDK
      ansible.builtin.apt:
        name: openjdk-{{ bamboo_master_openjdk_version.split('.')[-2] }}-jdk
        cache_valid_time: 1800

    - name: Set default java to OpenJDK
      community.general.alternatives:
        name: java
        path: /usr/lib/jvm/java-8-openjdk-arm64/jre/bin/java

- name: Import bamboo task
  ansible.builtin.import_tasks: bamboo.yml

- name: Import facts task
  ansible.builtin.import_tasks: facts.yml
