---
#
# Ansible managed
#
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  name: docker
platforms:
  - name: "bamboo-${image:-fedora}-${tag:-latest}${TOX_ENVNAME}"
    image: "${namespace:-buluma}/${image:-fedora}:${tag:-latest}"
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    published_ports:
      - 8085/tcp
      - 127.0.0.1:8085/tcp
      - 127.0.0.1:8085
      - 0.0.0.0:8085->8085/tcp 
provisioner:
  name: ansible
verifier:
  name: ansible
